var _yt_www={};(function(g){var window=this;var baa,caa,Ba,ab,kaa,bb,cb,db,eb,jb,laa,kb,maa,naa,rb,Cb,Sb,oc,uaa,vaa,taa,Uc,Vc,ad,cd,yaa,hd,ld,fd,dd,Aaa,kd,id,jd,nd,zaa,sd,Baa,Caa,Jd,Od,Qd,Rd,Sd,Gaa,Faa,ge,te,Haa,De,Ke,Je,Jaa,Kaa,Le,Me,Oe,Maa,Se,Ye,Xe,Te,bf,Raa,ff,cf,df,Qaa,jf,hf,lf,We,Qe,Pe,Re,mf,$e,kf,af,of,Taa,Paa,uf,vf,yf,Bf,Df,Rf,Tf,Uf,Xf,Zf,$f,ag,dg,cg,fg,bg,gg,Vf,Yf,cba,hg,ig,dba,eba,pg,rg,tg,gba,Ag,Bg,Eg,Cg,hba,Lg,Sg,Rg,iba,Wg,oba,nba,mba,bh,lba,jba,kba,pba,ih,qba,jh,lh,rba,sba,mh,nh,sh,wh,xh,yh,Bh,Ch,Dh,yba,zba,th,vh,rh,xba,uh,Cba,
Lh,Kh,Mh,Bba,Dba,Eba,Nh,Oh,ma,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.n=function(a,b,c){a=a.split(".");c=c||g.m;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.q=function(a,b){a=a.split(".");b=b||g.m;for(var c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
g.da=function(){};
g.r=function(){throw Error("unimplemented abstract method");};
g.ea=function(a){a.getInstance=function(){return a.Fc?a.Fc:a.Fc=new a}};
g.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ga=function(a){return"array"==g.fa(a)};
g.ha=function(a){var b=g.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ia=function(a){return"string"==typeof a};
g.ja=function(a){return"number"==typeof a};
g.ka=function(a){return"function"==g.fa(a)};
g.la=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.na=function(a){return a[ma]||(a[ma]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.t=function(a,b,c){g.t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.t.apply(null,arguments)};
g.v=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.w=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.t0=function(a,c,h){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
g.oa=function(a){g.oa[" "](a);return a};
g.qa=function(a,b){try{return g.oa(a[b]),!0}catch(c){}return!1};
g.ra=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
g.sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ua=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return/^[\s\xa0]*$/.test(a)};
g.wa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return null==a?"":String(a)};
g.Ca=function(a,b){var c=0;a=(0,g.Aa)(String(a)).split(".");b=(0,g.Aa)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var h=a[e]||"",k=b[e]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;c=Ba(0==h[1].length?0:(0,window.parseInt)(h[1],10),0==k[1].length?0:(0,window.parseInt)(k[1],10))||Ba(0==h[2].length,0==k[2].length)||Ba(h[2],k[2]);h=h[3];k=k[3]}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Ga=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.ia(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.ia(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ia=function(a,b){return 0<=(0,g.Ha)(a,b)};
g.Ka=function(a,b){b=(0,g.Ha)(a,b);var c;(c=0<=b)&&g.Ja(a,b);return c};
g.Ja=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.La=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Ma=function(a){return function(){return a}};
g.Na=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Oa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Pa=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Qa=function(a){for(var b in a)return!1;return!0};
g.Ra=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Va.length;h++)c=Va[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.ya(g.Xa,a)};
g.Za=function(){return g.Ya("Trident")||g.Ya("MSIE")};
g.$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!g.Ya("Edge")};
ab=function(a){g.m.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Za()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.wq;c.wq=null;a()}};
return function(a){d.next={wq:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.m.setTimeout(a,0)}};
bb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
cb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
db=function(){this.C=this.A=null};
eb=function(){this.next=this.scope=this.uc=null};
jb=function(a,b){fb||laa();gb||(fb(),gb=!0);var c=hb,d=ib.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.m.Promise&&g.m.Promise.resolve){var a=g.m.Promise.resolve(void 0);fb=function(){a.then(kb)}}else fb=function(){var a=kb;
!g.ka(g.m.setImmediate)||g.m.Window&&g.m.Window.prototype&&!g.Ya("Edge")&&g.m.Window.prototype.setImmediate==g.m.setImmediate?(lb||(lb=kaa()),lb(a)):g.m.setImmediate(a)}};
kb=function(){for(var a;a=hb.remove();){try{a.uc.call(a.scope)}catch(b){ab(b)}cb(ib,a)}gb=!1};
g.mb=function(){this.rd=this.rd;this.Jb=this.Jb};
g.pb=function(a,b){g.nb(a,g.v(g.ob,b))};
g.nb=function(a,b){a.rd?g.ca(void 0)?b.call(void 0):b():(a.Jb||(a.Jb=[]),a.Jb.push(g.ca(void 0)?(0,g.t)(b,void 0):b))};
g.ob=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.qb=function(a){g.mb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.Ed={};this.F=!!a};
maa=function(a,b,c){jb(function(){a.apply(b,c)})};
g.tb=function(a){rb(g.sb,arguments)};
g.y=function(a,b){return a in g.sb?g.sb[a]:b};
g.vb=function(a,b){g.ka(a)&&(a=g.ub(a));return window.setTimeout(a,b)};
g.wb=function(a,b){g.ka(a)&&(a=g.ub(a));return window.setInterval(a,b)};
g.xb=function(a){window.clearTimeout(a)};
g.yb=function(a){window.clearInterval(a)};
g.ub=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.zb(b),b;}}:a};
g.zb=function(a,b,c,d,e){var h=g.q("yt.logging.errors.log");h?h(a,b,c,d,e):(h=g.y("ERRORS",[]),h.push([a,b,c,d,e]),g.tb("ERRORS",h))};
naa=function(a,b,c,d,e){var h=!1;if(g.sb.Ip&&g.sb.Ip.log_window_onerror_fraction&&Math.random()<g.sb.Ip.log_window_onerror_fraction)h=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,p=k.length;l<p;l++)if(0<k[l].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.zb(e))};
g.Bb=function(a){return a in g.Ab};
rb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else for(c in b=b[0],b)a[c]=b[c]};
g.z=function(a,b,c){var d=Cb();if(d){var e=d.subscribe(a,function(){if(!Db||Db!=e){var d=arguments,k;k=function(){Eb[e]&&b.apply(c||window,d)};
try{Fb[a]?k():g.vb(k,0)}catch(l){g.zb(l)}}},c);
Eb[e]=!0;Gb[a]||(Gb[a]=[]);Gb[a].push(e);return e}return 0};
g.Hb=function(a){var b=Cb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.A)(a,function(a){b.unsubscribeByKey(a);delete Eb[a]}))};
g.B=function(a,b){var c=Cb();return c?c.publish.apply(c,arguments):!1};
g.Ib=function(a,b){Fb[a]=!0;var c=Cb(),c=c?c.publish.apply(c,arguments):!1;Fb[a]=!1;return c};
Cb=function(){return g.q("yt.pubsub.instance_")};
g.Jb=function(){return!!g.q("yt.scheduler.instance")};
g.Kb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.q("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.vb(a,b||0)};
g.Lb=function(a,b){return g.Kb(a,b)};
g.Nb=function(a){if(!(0,window.isNaN)(a)){var b=g.q("yt.scheduler.instance.cancelJob");b?b(a):g.xb(a)}};
g.Ob=function(a){for(var b=0,c=a.length;b<c;b++)g.Nb(a[b])};
g.Pb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.ub(d):null;this.F=e?g.ub(e):null;this.D=[];this.A=this.C=0};
g.Qb=function(a){g.Nb(a.C);a.C=g.Lb((0,g.t)(a.init,a))};
g.Tb=function(a){a.name in Rb&&Sb(a.name);Rb[a.name]={reqs:[],disable:(0,g.t)(a.disable,a)};(0,g.A)(a.deps,function(b){if(!(b in Rb))throw Error("Module "+b+" required by "+a.name);Rb[b].reqs.push(a.name)});
a.enable()};
Sb=function(a){if(a in Rb){var b=Rb[a];(0,g.A)(b.reqs,function(a){Sb(a)});
try{b.disable()}catch(c){}delete Rb[a]}};
g.Vb=function(){this.A="";this.C=g.Ub};
g.Wb=function(a){var b=new g.Vb;b.A=a;return b};
g.Yb=function(){this.A="";this.C=Xb};
g.Zb=function(a){if(a instanceof g.Yb&&a.constructor===g.Yb&&a.C===Xb)return a.A;g.fa(a);return"type_error:SafeUrl"};
g.ac=function(a){if(a instanceof g.Yb)return a;a=a.mg?a.hf():String(a);oaa.test(a)||(a="about:invalid#zClosurez");return g.$b(a)};
g.$b=function(a){var b=new g.Yb;b.A=a;return b};
g.cc=function(){this.A="";this.B=g.bc;this.C=null};
g.dc=function(a,b){var c=new g.cc;c.A=a;c.C=b;return c};
g.ec=function(a,b){b=b instanceof g.Yb?b:g.ac(b);a.href=g.Zb(b)};
g.C=function(a,b){return a?a.dataset?a.dataset[g.fc(b)]:a.getAttribute("data-"+b):null};
g.fc=function(a){return gc[a]||(gc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.ic=function(a,b){var c=g.hc(a);window.spf.script.load(a,c,b)};
g.hc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(paa,""),b=b.replace(qaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.jc=function(a){if(a.classList)return a.classList;a=a.className;return g.ia(a)&&a.match(/\S+/g)||[]};
g.D=function(a,b){return a.classList?a.classList.contains(b):g.Ia(g.jc(a),b)};
g.kc=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.lc=function(a,b){return a==b?!0:a&&b?a.x==b.x&&a.y==b.y:!1};
g.mc=function(a,b){this.width=a;this.height=b};
g.nc=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
oc=function(){var a=g.m.document;return a?a.documentMode:void 0};
g.qc=function(a){return g.ra(raa,a,function(){return 0<=g.Ca(g.pc,a)})};
g.sc=function(a){return Number(g.rc)>=a};
g.E=function(a){return g.ia(a)?window.document.getElementById(a):a};
g.tc=function(a){return g.ia(a)?window.document.getElementById(a):a};
g.vc=function(a,b){g.Na(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:uc.hasOwnProperty(d)?a.setAttribute(uc[d],b):g.ua(d,"aria-")||g.ua(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.xc=function(a){return g.wc(a||window)};
g.wc=function(a){a=a.document;a=g.yc(a)?a.documentElement:a.body;return new g.mc(a.clientWidth,a.clientHeight)};
g.Ac=function(a){var b=g.zc(a);a=a.parentWindow||a.defaultView;return g.F&&g.qc("10")&&a.pageYOffset!=b.scrollTop?new g.kc(b.scrollLeft,b.scrollTop):new g.kc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.zc=function(a){return a.scrollingElement?a.scrollingElement:!g.Bc&&g.yc(a)?a.documentElement:a.body||a.documentElement};
g.Dc=function(a,b,c){return g.Cc(window.document,arguments)};
g.Cc=function(a,b){var c=String(b[0]),d=b[1];if(!saa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ia(d)?c.className=d:g.ga(d)?c.className=d.join(" "):g.vc(c,d));2<b.length&&g.Ec(a,c,b,2);return c};
g.Ec=function(a,b,c,d){function e(c){c&&b.appendChild(g.ia(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ha(h)||g.la(h)&&0<h.nodeType?e(h):(0,g.A)(taa(h)?g.La(h):h,e)}};
g.yc=function(a){return"CSS1Compat"==a.compatMode};
g.Fc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Gc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Hc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
uaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
vaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Ic=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
taa=function(a){if(a&&"number"==typeof a.length){if(g.la(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ka(a))return"function"==typeof a.item}return!1};
g.Jc=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Mc=function(a){var b=a.__yt_uid_key;b||(b=Lc(),a.__yt_uid_key=b);return b};
g.Nc=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.A)(a.childNodes,function(a){b.appendChild(g.Nc(a))}):b.innerHTML=a.innerHTML;
return b};
g.Oc=function(){var a=window.document;if("visibilityState"in a)return a.visibilityState;var b=waa+"VisibilityState";if(b in a)return a[b]};
g.Pc=function(a){return!!g.y("EXPERIMENT_FLAGS",{})[a]};
g.Qc=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};
g.Rc=function(a){a=String(a);if(g.Qc(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};
g.Tc=function(a,b){return(new g.Sc(b)).Wb(a)};
g.Sc=function(a){this.A=a};
Uc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(g.ga(b)){var d=b;b=d.length;c.push("[");for(var e="",h=0;h<b;h++)c.push(e),e=d[h],Uc(a,a.A?a.A.call(d,String(h),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");h="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(h),Vc(d,c),c.push(":"),Uc(a,a.A?a.A.call(b,d,e):e,c),h=","));c.push("}");return}}switch(typeof b){case "string":Vc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};
Vc=function(a,b){b.push('"',a.replace(xaa,function(a){var b=Wc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Wc[a]=b);return b}),'"')};
g.Xc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.Yc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.$c=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.H=!1;if(a!=g.da)try{var c=this;a.call(b,function(a){g.Zc(c,2,a)},function(a){g.Zc(c,3,a)})}catch(d){g.Zc(this,3,d)}};
ad=function(){this.next=this.context=this.C=this.B=this.A=null;this.D=!1};
cd=function(a,b,c){var d=bd.get();d.B=a;d.C=b;d.context=c;return d};
yaa=function(a,b,c){dd(a,b,c,null)||jb(g.v(b,a))};
g.ed=function(a){return new g.$c(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,p;l<a.length;l++)p=a[l],yaa(p,g.v(h,l),k);
else b(e)})};
g.gd=function(a,b){fd(a,null,b,void 0)};
hd=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,h=null,k=c.C;k&&(k.D||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(h=k);e&&(0==c.A&&1==d?hd(c,b):(h?(d=h,d.next==c.D&&(c.D=d),d.next=d.next.next):id(c),jd(c,e,3,b)))}a.B=null}else g.Zc(a,3,b)};
ld=function(a,b){a.C||2!=a.A&&3!=a.A||kd(a);a.D?a.D.next=b:a.C=b;a.D=b};
fd=function(a,b,c,d){var e=cd(null,null,null);e.A=new g.$c(function(a,k){e.B=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.ca(e)&&b instanceof g.md?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;ld(a,e);return e.A};
g.Zc=function(a,b,c){0==a.A&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,dd(c,a.R,a.Z,a)||(a.K=c,a.A=b,a.B=null,kd(a),3!=b||c instanceof g.md||zaa(a,c)))};
dd=function(a,b,c,d){if(a instanceof g.$c)return ld(a,cd(b||g.da,c||null,d)),!0;if(g.Yc(a))return a.then(b,c,d),!0;if(g.la(a))try{var e=a.then;if(g.ka(e))return Aaa(a,e,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1};
Aaa=function(a,b,c,d,e){function h(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,h)}catch(p){h(p)}};
kd=function(a){a.H||(a.H=!0,jb(a.G,a))};
id=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
jd=function(a,b,c,d){if(3==c&&b.C&&!b.D)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,nd(b,c,d);else try{b.D?b.B.call(b.context):nd(b,c,d)}catch(e){od.call(null,e)}cb(bd,b)};
nd=function(a,b,c){2==b?a.B.call(a.context,c):a.C&&a.C.call(a.context,c)};
zaa=function(a,b){a.F=!0;jb(function(){a.F&&od.call(null,b)})};
g.md=function(a){g.sa.call(this,a)};
g.pd=function(){return{apiaryHost:g.y("APIARY_HOST",void 0),gq:g.y("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.y("GAPI_HINT_OVERRIDE"),gapiHintParams:g.y("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.y("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.y("INNERTUBE_API_VERSION",void 0),tF:g.y("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.y("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),vF:g.y("INNERTUBE_CONTEXT_HL",void 0),uF:g.y("INNERTUBE_CONTEXT_GL",void 0),TQ:g.y("XHR_APIARY_HOST",
void 0)}};
g.qd=function(a){a={client:{hl:a.vF,gl:a.uF,clientName:a.tF,clientVersion:a.innertubeContextClientVersion}};g.y("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.y("DELEGATED_SESSION_ID")});return a};
sd=function(){this.A=g.pd();rd||(rd=Baa(this.A))};
Baa=function(a){return(new g.$c(function(b){g.ic(g.y("GAPI_LOADER_URL",void 0),function(){try{g.q("yt.gapi.load")("client",{gapiHintOverride:a.gapiHintOverride,_c:{jsl:{h:a.gapiHintParams}},callback:b})}catch(c){g.zb(c)}})})).then(function(){})};
Caa=function(a,b,c,d){var e={path:"/youtubei/"+a.A.innertubeApiVersion+"/"+b,headers:{"X-Goog-Visitor-Id":g.y("VISITOR_DATA")},method:"POST",body:g.Tc(c)},h=(0,g.t)(a.D,a);rd.then(function(){h();g.q("gapi.client.request")(e).execute(d||g.da)})};
g.td=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.ud=function(a){var b={};void 0!==a.A?b.trackingParams=a.A:(b.veType=a.B,null!=a.C&&(b.veCounter=a.C));return b};
g.zd=function(a,b){g.vd[a.endpoint]=g.vd[a.endpoint]||[];var c=g.vd[a.endpoint];c.push(a.Db);wd[a.endpoint]=b;20<=c.length?g.xd():g.yd()};
g.xd=function(){g.xb(g.Ad);if(!g.Qa(g.vd)){for(var a in g.vd){var b=g.Bd[a];if(!b){b=wd[a];if(!b)continue;b=new b;g.Bd[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.Cd)());c[Daa[a]]=g.vd[a];b.B(a,c,{});delete g.vd[a]}g.Qa(g.vd)||g.yd()}};
g.yd=function(){g.xb(g.Ad);g.Ad=g.vb(g.xd,g.y("LOGGING_BATCH_TIMEOUT",1E4))};
g.Dd=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.Cd)());e[a]=b;g.zd({endpoint:"log_event",Db:e},c)};
g.Ed=function(){};
g.Gd=function(a){if(a instanceof g.Ed)return a;if("function"==typeof a.Zb)return a.Zb(!1);if(g.ha(a)){var b=0,c=new g.Ed;c.next=function(){for(;;){if(b>=a.length)throw g.Fd;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");};
g.Hd=function(a,b,c){if(g.ha(a))try{(0,g.A)(a,b,c)}catch(d){if(d!==g.Fd)throw d;}else{a=g.Gd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Fd)throw d;}}};
g.Id=function(a){if(g.ha(a))return g.La(a);a=g.Gd(a);var b=[];g.Hd(a,function(a){b.push(a)});
return b};
Jd=function(){};
g.Kd=function(){};
g.Ld=function(a){this.A=a};
g.Md=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.A=a};
Od=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.A=a};
g.Pd=function(a){this.A=a};
Qd=function(a){this.A=a};
Rd=function(a){this.data=a};
Sd=function(a){return!g.ca(a)||a instanceof Rd?a:new Rd(a)};
g.Td=function(a){this.A=a};
g.Vd=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,g.Ud)()||!!b&&b>(0,g.Ud)()};
g.Wd=function(a){this.A=a};
g.Zd=function(a){if(!g.Xd&&!g.Yd||!window.JSON)return null;var b;try{b=g.Xd.get(a)}catch(c){}if(!g.ia(b))try{b=g.Yd.get(a)}catch(c){}if(!g.ia(b))return null;try{b=JSON.parse(b,void 0)}catch(c){}return b};
g.$d=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Eaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.jo=a.pageX;this.lo=a.pageY}};
g.ae=function(a){if(g.ha(a))return Faa(a);if(g.la(a)&&!g.ka(a)&&!(g.la(a)&&0<a.nodeType))return Gaa(a);try{return g.m.JSON.stringify(a),a}catch(b){}};
Gaa=function(a){var b={};g.Na(a,function(a,d){b[d]=g.ae(a)});
return b};
Faa=function(a){var b=[];(0,g.A)(a,function(a,d){b[d]=g.ae(a)});
return b};
g.ce=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Pa(g.be,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.G=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.ce(a,b,c,d);if(e)return e;var e=++de.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.$d(d);if(!g.Jc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.$d(b);
b.currentTarget=a;return c.call(a,b)};
k=g.ub(k);a.addEventListener?("mouseenter"==b&&h?b="mouseover":"mouseleave"==b&&h?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.be[e]=[a,b,c,k,d];return e};
g.ee=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.A)(a,function(a){if(a in g.be){var b=g.be[a],d=b[0],e=b[1],h=b[3],b=b[4];d.removeEventListener?d.removeEventListener(e,h,b):d.detachEvent&&d.detachEvent("on"+e,h);delete g.be[a]}}))};
g.fe=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.he=function(){if(null==g.q("_lact",window)){var a=(0,window.parseInt)(g.y("LACT"),10),a=(0,window.isFinite)(a)?(0,g.Ud)()-Math.max(a,0):-1;g.n("_lact",a,window);-1==a&&ge();g.G(window.document,"keydown",ge);g.G(window.document,"keyup",ge);g.G(window.document,"mousedown",ge);g.G(window.document,"mouseup",ge);g.z("page-mouse",ge);g.z("page-scroll",ge);g.z("page-resize",ge)}};
ge=function(){null==g.q("_lact",window)&&(g.he(),g.q("_lact",window));var a=(0,g.Ud)();g.n("_lact",a,window);g.B("USER_ACTIVE")};
g.ie=function(){var a=g.q("_lact",window);return null==a?-1:Math.max((0,g.Ud)()-a,0)};
g.je=function(){return g.Zd("yt-interaction-logging-parent")};
g.ke=function(){var a=g.y("client-screen-nonce",void 0);a||(a=g.y("EVENT_ID",void 0));return a};
g.le=function(a,b,c,d,e,h,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);h&&(l+="?"+h);k&&(l+="#"+k);return l};
g.me=function(a){return a?(0,window.decodeURI)(a):a};
g.oe=function(a,b){return b.match(g.ne)[a]||null};
g.pe=function(a){return g.me(g.oe(3,a))};
g.qe=function(a){a=a.match(g.ne);return g.le(null,null,null,null,a[5],a[6],a[7])};
g.re=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.se=function(a,b,c){if(g.ga(b))for(var d=0;d<b.length;d++)g.se(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.wa(b))};
te=function(a,b){for(var c in b)g.se(c,b[c],a);return a};
g.ue=function(a){a=te([],a);a[0]="";return a.join("")};
g.ve=function(a,b){return g.re(te([a],b))};
g.we=function(a,b,c){a&&(c&&(c=g.Xa,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Dc("IFRAME",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Ic(a).body.appendChild(a)):Haa(a,b))};
g.xe=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.we(a,void 0)}catch(b){g.we(a,void 0)}};
Haa=function(a,b){var c=new window.Image,d=""+Iaa++;ye[d]=c;c.onload=c.onerror=function(){b&&ye[d]&&b();delete ye[d]};
c.src=a};
g.ze=function(a,b){this.version=a;this.args=b};
g.Ae=function(a,b){this.topic=a;this.Mf=b};
g.Ce=function(a,b){var c=g.Be();return c?c.publish.call(c,a.toString(),a,b):!1};
g.Be=function(){return g.q("yt.pubsub2.instance_")};
De=function(a){g.ze.call(this,1,arguments)};
g.Ee=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Fe=function(a,b){return a&&b?b instanceof g.Ee?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Ge=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.He=function(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top);b=Math.min(a.top+a.height,b.top+b.height);if(e<=b)return a.left=c,a.top=e,a.width=d-c,a.height=b-e,!0}return!1};
g.Ie=function(a){return new g.mc(a.width,a.height)};
Ke=function(a){this.A=a||window;this.R=this.B=0;if(this.A.performance&&this.A.performance.timing&&this.A.performance.getEntriesByType){a=g.xc(this.A);this.G=new g.Ge(0,0,a.width,a.height);a=[];for(var b=this.A.document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++){var e=b[c];if("IMG"==e.tagName||"IFRAME"==e.tagName){var h=Je(this,e,e.src);if(h){if("IFRAME"==e.tagName){var k;try{k=(new Ke(e.contentWindow)).B}catch(l){k=0}0<k&&(h.timing=k)}a.push(h)}}(h=this.A.getComputedStyle(e)["background-image"])&&
(h=Ke.A.exec(h))&&1<h.length&&(h=Je(this,e,h[1]))&&a.push(h)}this.C=a;this.F=this.A.performance.getEntriesByType("resource");this.K=this.A.performance.getEntriesByType("mark");k={};a=0;for(b=this.F.length;a<b;a++)c=this.F[a],k[c.name]=c.responseEnd;a=0;for(b=this.K.length;a<b;a++)c=this.K[a],"mark_iframe_loaded: "==c.name.slice(0,20)&&(k[c.name.slice(20)]=c.startTime);a=0;for(b=this.C.length;a<b;a++)c=this.C[a],c.timing||(c.timing=k[c.url]||0);this.H=Jaa(this);this.D=Kaa(this);e=k=0;if(this.D.length)for(b=
a=0,c=this.D.length;b<c;b++)d=this.D[b],e=d.timing-e,0<e&&1>a&&(k+=(1-a)*e),e=d.timing,a=d.progress;this.B=Math.round(k||this.H);this.R=e}};
Je=function(a,b,c){return c&&b.getBoundingClientRect&&(b=b.getBoundingClientRect(),b=new g.Ge(b.left,b.top,b.width,b.height),g.He(b,a.G))?new Le(b,c):null};
Jaa=function(a){var b,c=a.A,d=c.performance.timing.navigationStart;if("msFirstPaint"in c.performance.timing)b=c.performance.timing.A-d;else if("chrome"in c&&"loadTimes"in c.chrome){var e=c.chrome.loadTimes(),h=e.firstPaintTime;if(0<h){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);h>=k&&(b=1E3*(h-k))}}if(void 0===b||0>b||12E4<b){b=c.performance.timing.responseStart-d;for(var l={},c=c.document.getElementsByTagName("head")[0].children,d=0,e=c.length;d<e;d++)h=c[d],"SCRIPT"==h.tagName&&h.src&&
!h.async?l[h.src]=!0:"LINK"==h.tagName&&"stylesheet"==h.rel&&h.href&&(l[h.href]=!0);a.F.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===b||a>b)b=a})}return Math.max(b,0)||0};
Kaa=function(a){for(var b={0:0},c=0,d=a.H,e=0,h=a.C.length;e<h;e++){var k=a.C[e],l=d;k.timing>d&&(l=k.timing);b[l]||(b[l]=0);k=g.Ie(k.region).Lg();b[l]+=k;c+=k}e=g.Ie(a.G).Lg();0<e&&(e=.1*Math.max(e-c,0),d in b||(b[d]=0),b[d]+=e,c+=e);d=[];if(c){for(var p in b)a=new Me((0,window.parseFloat)(p),b[p]),d.push(a);d.sort(function(a,b){return a.timing-b.timing});
e=b=0;for(h=d.length;e<h;e++)a=d[e],b+=a.Lg,a.progress=b/c}return d};
Le=function(a,b){this.region=a;this.url=b};
Me=function(a,b){this.Lg=b;this.timing=a};
Oe=function(a){Ne.mark&&(Laa.test(a)||(a="mark_"+a),Ne.mark(a))};
Maa=function(){if("cold"==Pe().yt_lt){var a=Qe(),b=Re(),c;for(c in a)g.ua(c,"_")||"tick_"+c in b||Se(c,a[c]);a=Pe();for(c in a)"info_"+c in b||Te(c,a[c])}};
g.Ve=function(a,b,c){b||"_"==a[0]||Oe(a);var d=Qe(c),e=b||(0,g.Cd)();d[a]&&(d["_"+a]=d["_"+a]||[d[a]],d["_"+a].push(e));d[a]=e;Se(a,b,c)||g.Ue(!1,c);return d[a]};
Se=function(a,b,c){Re(c)["tick_"+a]=b;return g.Pc("csi_on_gel")?(c=We(c),"_start"==a?g.Dd("latencyActionBaselined",{clientActionNonce:c},sd,b):g.Dd("latencyActionTicked",{tickName:a,clientActionNonce:c},sd,b),!0):!1};
Ye=function(a,b){Xe("yt_sts",a,void 0);g.Ve("_start",b,void 0)};
Xe=function(a,b,c){Pe(c)[a]=b;Te(a,b,c)};
Te=function(a,b,c){Re(c)["info_"+a]=b;if(g.Pc("csi_on_gel"))if(a in Ze){var d={};a=Ze[a];g.Ia(Naa,a)&&(b=!!b);d[a]=b;b=We(c);d.clientActionNonce=b;g.Dd("latencyActionInfo",d,sd)}else g.zb(Error("Unknown label "+a+" logged with GEL CSI."))};
bf=function(a){$e(a);Oaa();af(!1,a)};
Raa=function(){var a=g.y("TIMING_INFO",{}),b;for(b in a)Xe(b,a[b]);(a=g.ke())&&Xe("csn",a);(a=g.y("PREVIOUS_ACTION",void 0))&&Xe("pa",a);b=Pe();b.p=g.y("CLIENT_PROTOCOL")||"unknown";b.t=g.y("CLIENT_TRANSPORT")||"unknown";Ne.now&&Ne.timing?(a=Ne.timing.navigationStart+Ne.now(),a=Math.round((0,g.Ud)()-a)):a=null;null!=a&&Xe("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&Xe("ba",1);Xe("yt_vis",Paa());if("cold"==b.yt_lt){a=Ne.timing||{};g.Pc("cold_load_nav_start_web")&&a.navigationStart&&
(1==b.prerender?g.Ve("srt",0):(Ye("n",a.navigationStart),g.Ve("srt",a.responseStart)));a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=b.loadTimes,g.ka(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.Ve("fpt",b);cf(a);Ne.getEntriesByType&&Qaa();a=g.y("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.y("TIMING_ACTION",void 0);
a&&-1<a.indexOf(b)&&(a=(0,g.Cd)(),b=new Ke,c=(0,g.Cd)(),0<b.B&&(Xe("si",b.B),g.Ve("vsc",df(b.R)),g.Ve("sics",a),g.Ve("sice",c)));a=[];if(window.document.querySelector&&Ne&&Ne.getEntriesByName)for(var d in ef){b=a;var c=ef[d],e=window.document.querySelector(d);if(e){var h="",k=e.nodeName;"SCRIPT"==k?h=e.src:"LINK"==k&&(h=e.href);h&&(e=Ne.getEntriesByName(h))&&e[0]&&b.push(c+"."+Math.round(e[0].duration))}}a.length&&Xe("rs",a.join(","))}};
ff=function(a){var b=Qe(a);if(b.aft)return b.aft;a=g.y((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
cf=function(a){g.Ve("nreqs",a.requestStart,void 0);g.Ve("nress",a.responseStart,void 0);g.Ve("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.Ve("nrs",a.redirectStart,void 0),g.Ve("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.Ve("ndnss",a.domainLookupStart,void 0),g.Ve("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.Ve("ntcps",a.connectStart,void 0),g.Ve("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.Ve("nstcps",a.secureConnectionStart,void 0),g.Ve("ntcpe",a.connectEnd,void 0))};
df=function(a){return Math.round(Ne.timing.navigationStart+a)};
Qaa=function(){var a=window.location.protocol,b=Ne.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.Ve("wfcs",df(c.startTime)),g.Ve("wfce",df(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.Ve("wffs",df(b.startTime)),g.Ve("wffe",df(b.responseEnd)))};
jf=function(a){var b=Qe(a),c=Pe(a),d=b._start,e;for(e in b)if(g.ua(e,"_")&&g.ga(b[e])){var h=e.slice(1);if(h in Saa){var k=(0,g.gf)(b[e],function(a){return Math.round(a-d)});
c["all_"+h]=k.join()}delete b[e]}h=!!c.ap;if(k=g.q("yt.timing.reportbuilder_")){if(k=k(b,c,a))hf(k,h),bf(a)}else{var l=g.y("CSI_SERVICE_NAME","youtube"),k={v:2,s:l,action:g.y((a||"")+"TIMING_ACTION",void 0)},p=c.srt;delete c.srt;void 0===b.srt&&(p||0===p||(p=Ne.timing||{},p=Math.max(0,p.responseStart-p.navigationStart),(0,window.isNaN)(p)&&c.pt&&(p=c.pt)),p||0===p)&&(c.srt=Math.round(p));if(c.h5jse){var u=window.location.protocol+g.q("ytplayer.config.assets.js");(u=Ne.getEntriesByName?Ne.getEntriesByName(u)[0]:
null)?c.h5jse=Math.round(c.h5jse-u.responseEnd):delete c.h5jse}b.aft=ff(a);Taa(a)&&"youtube"==l&&(Xe("yt_lt","hot_bg",a),l=b.vc,u=b.pbs,delete b.aft,c.aft=Math.round(u-l));for(var x in c)"_"!=x.charAt(0)&&(k[x]=c[x]);b.ps=(0,g.Cd)();c={};x=[];for(e in b)"_"!=e.charAt(0)&&(l=Math.round(b[e]-d),c[e]=l,x.push(e+"."+l));k.rt=x.join(",");(b=g.q("ytdebug.logTiming"))&&b(k,c);g.Pc("navigation_only_csi_reset")||bf(a);hf(k,h,a);g.Ce(Uaa,new De(c.aft+(p||0)))}};
g.Ue=function(a,b){if(!kf(b)||!g.Pc("navigation_only_csi_reset")&&!b){var c=g.y((b||"")+"TIMING_ACTION",void 0),d=Qe(b);if(g.q("yt.timing."+(b||"")+"ready_")&&c&&d._start&&ff(b))if(a||b)jf(b);else{a=!0;c=g.y("TIMING_WAIT",[]);if(c.length)for(var e=0,h=c.length;e<h;++e)if(!(c[e]in d)){a=!1;break}a&&jf(b)}}};
hf=function(a,b,c){if(g.Pc("debug_csi_data")){var d=g.q("yt.timing.csiData");d||(d=[],g.n("yt.timing.csiData",d,void 0));d.push({page:window.location.href,time:new Date,args:a})}var d="",e;for(e in a)d+="&"+e+"="+a[e];a="/csi_204?"+d.substring(1);window.navigator&&window.navigator.sendBeacon&&b?g.xe(a):g.we(a);af(!0,c)};
lf=function(a){g.n("yt.timing.ready_",a,void 0)};
We=function(a){var b=mf(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(h){}c=Array(16);for(d=0;16>d;d++){e=(0,g.Ud)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(nf)for(d=1,e=0;e<nf.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^nf.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");mf(a).nonce=b}return b};
Qe=function(a){return mf(a).tick};
Pe=function(a){return mf(a).info};
Re=function(a){a=mf(a);"gel"in a||(a.gel={});return a.gel};
mf=function(a){return g.q("ytcsi."+(a||"")+"data_")||$e(a)};
$e=function(a){var b={tick:{},info:{}};g.n("ytcsi."+(a||"")+"data_",b,void 0);return b};
kf=function(a){return!!g.q("yt.timing."+(a||"")+"pingSent_")};
af=function(a,b){g.n("yt.timing."+(b||"")+"pingSent_",a,void 0)};
of=function(a){if(!kf(void 0)){if(!g.Pc("send_empty_timing")){var b=g.y("CSI_SERVICE_NAME","youtube");if(!g.y("TIMING_ACTION",void 0)||!b)return}g.Ve("aa",void 0,void 0);Xe("ap",1,void 0);Xe("yt_fss",a,void 0);jf(void 0)}};
Taa=function(a){var b=Qe(a),c=b.pbr,d=b.vc,b=b.pbs;return c&&d&&b&&c<d&&d<b&&1==Pe(a).yt_pvis};
Paa=function(){switch(g.Oc()){case "hidden":return 0;case "visible":return 1;case "prerender":return 2;case "unloaded":return 3}return-1};
g.pf=function(a){this.A=a||{cookie:""}};
g.rf=function(a){a=(a.A.cookie||"").split(g.qf);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.tf=function(a,b,c,d){g.sf.set(""+a,b,c,"/",d||"youtube.com")};
g.wf=function(a,b,c){var d=g.y("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.pe(window.location.href);e&&d.push(e);e=g.pe(a);if(g.Ia(d,e)||!e&&g.ua(a,"/"))if(a=g.qe(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))g.Pc("enable_more_related_ve_logging")&&(b.itct||b.ved)&&(b.csn=b.csn||g.ke()),c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(uf(a,b,c),vf(b))):(uf(a,b),vf(b))};
uf=function(a,b,c){a="ST-"+g.Da(a).toString(36);c=c||5;b=b?g.ue(b):"";g.tf(a,b,c)};
vf=function(a){if(a){a=a.itct||a.ved;var b=g.q("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.td(a))}};
g.xf=function(a,b){g.we("/gen_204?"+a,b)};
yf=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Vaa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Waa);this.params=a.params||g.Ua(Xaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.zf=function(a){a instanceof yf||(a=new yf(a));return a};
Bf=function(){return null!=g.Af};
g.Cf=function(){return g.Af?g.Af.invoke():null};
Df=function(){return(0,window.parseInt)(g.y("DCLKSTAT",0),10)};
g.Ef=function(a,b,c){c=c||"";g.ec(window.location,g.ve(a,b||{})+c)};
g.Ff=function(a,b){b&&g.wf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.Ef(a)};
g.Gf=function(a,b,c){var d=g.y("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.wf(a,b);if(c)return!1;g.Ff(a);return!0};
g.Hf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.If=function(a,b){a.style.height=g.Hf(b,!0)};
g.Jf=function(a,b){a.style.width=g.Hf(b,!0)};
g.Lf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.q("window.navigator.plugins"),b=g.q("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,p,u;if(g.Kf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(x){k=null}else p=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=p.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(x){l=""}p&&u&&p.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
g.Mf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
g.Nf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
g.Of=function(a){return-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!g.Mf(a,9,1,58)?!1:!0};
g.Pf=function(a,b,c){if(b){a=g.ia(a)?g.tc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.ue(c.args);if(g.Kf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Qf=function(a,b){var c=a.match(Yaa);window.spf.style.load(a,c?c[1]:"",b)};
Rf=function(a){g.mb.call(this);this.A=[];this.C=a||this};
Tf=function(a,b,c,d){d=g.ub((0,g.t)(d,a.C));d={target:b,name:c,Nb:d};b.addEventListener(c,d.Nb,void 0);a.A.push(d)};
Uf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Nb)}};
Xf=function(a,b){g.mb.call(this);this.K=this.D=a;this.ka=b;this.H=!1;this.api={};this.na=this.U=null;this.Y=new g.qb;g.pb(this,this.Y);this.B={};this.G=this.Ga=this.C=this.kb=this.A=null;this.ba=!1;this.R=this.F=this.M=this.P=null;this.Ua={};this.Cb=["onReady"];this.ha=new Rf(this);g.pb(this,this.ha);this.mb=null;this.ub=window.NaN;this.ia={};Vf(this);this.ve("onDetailedError",(0,g.t)(this.DK,this));this.ve("onTabOrderChange",(0,g.t)(this.Jz,this));this.ve("onTabAnnounce",(0,g.t)(this.Zp,this));this.ve("WATCH_LATER_VIDEO_ADDED",
(0,g.t)(this.GK,this));this.ve("WATCH_LATER_VIDEO_REMOVED",(0,g.t)(this.HK,this));g.Wf||(this.ve("onMouseWheelCapture",(0,g.t)(this.lK,this)),this.ve("onMouseWheelRelease",(0,g.t)(this.mK,this)));this.ve("onAdAnnounce",(0,g.t)(this.Zp,this));this.Z=new Rf(this);g.pb(this,this.Z);this.eb=!1;this.bb=null};
Zf=function(a,b){a.kb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ka,a.A.attrs.id=a.ka);a.K.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ka;a.Ga||(a.Ga=Yf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;(b=a.A.attrs.width)&&g.Jf(a.K,Number(b)||b);(b=a.A.attrs.height)&&g.If(a.K,Number(b)||b)};
$f=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
ag=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=g.Mf(g.Lf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
dg=function(a,b){if((!b||(5!=(Zaa[b.errorCode]||5)?0:-1!=$aa.indexOf(b.errorCode)))&&ag(a)){(b=bg(a))&&b.stopVideo&&b.stopVideo();var c=a.A;b&&b.getUpdatedConfigurationData&&(b=b.getUpdatedConfigurationData(),c=g.zf(b));c.args.autoplay=1;c.args.html5_unavailable="1";Zf(a,c);cg(a,"flash")}};
cg=function(a,b){if(!a.hb()){if(!b){if(!(b=!a.A.html5&&ag(a))){if(!g.ca(a.A.disable.html5)){var c;b=!0;void 0!=a.A.args.deviceHasDisplay&&(b=a.A.args.deviceHasDisplay);if(2.2==eg)c=!0;else{a:{var d=b;b=g.q("yt.player.utils.videoElement_");b||(b=window.document.createElement("video"),g.n("yt.player.utils.videoElement_",b,void 0));try{if(b.canPlayType)for(var d=d?aba:bba,e=0;e<d.length;e++)if(b.canPlayType(d[e])){c=null;break a}c="fmt.noneavailable"}catch(h){c="html5.missingapi"}}c=!c}c&&(c=fg(a)||
a.A.assets.js);a.A.disable.html5=!c;c||(a.A.args.html5_unavailable="1")}b=!!a.A.disable.html5}b=b?ag(a)?"flash":"unsupported":"html5"}("flash"==b?a.RQ:a.SQ).call(a)}};
fg=function(a){var b=!0,c=bg(a);c&&a.A&&(a=a.A,b=g.C(c,"version")==a.assets.js);return b&&!!g.q("yt.player.Application.create")};
bg=function(a){var b=g.E(a.C);!b&&a.K&&a.K.querySelector&&(b=a.K.querySelector("#"+a.C));return b};
gg=function(a,b,c){var d=b[c];return function(){try{return a.mb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.mb=e,g.zb(e,"WARNING"))}}};
Vf=function(a){a.H=!1;if(a.na)for(var b in a.B)a.na(b,a.B[b]);for(var c in a.ia)g.xb((0,window.parseInt)(c,10));a.ia={};a.U=null;a.na=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.t)(a.ve,a);a.api.removeEventListener=(0,g.t)(a.YO,a);a.api.destroy=(0,g.t)(a.dispose,a);a.api.getLastError=(0,g.t)(a.iB,a);a.api.getPlayerType=(0,g.t)(a.zB,a);a.api.getCurrentVideoConfig=(0,g.t)(a.GA,a);a.api.loadNewVideoConfig=(0,g.t)(a.wp,a);a.api.isReady=(0,g.t)(a.fR,a)};
Yf=function(a,b){var c=b;if("string"==typeof b){if(a.Ua[b])return a.Ua[b];c=function(){var a=g.q(b);a&&a.apply(g.m,arguments)};
a.Ua[b]=c}return c?c:null};
cba=function(a,b){var c="ytPlayer"+b+a.ka;a.B[b]=c;g.m[c]=function(c){var d=g.vb(function(){a.hb()||(a.Y.Ha(b,c),g.Ra(a.ia,String(d)))},0);
g.Ta(a.ia,String(d),!0)};
return c};
hg=function(a){return(a=bg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
ig=function(a){g.Ve("dcp");a.cancel();Vf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=bg(a);"html5"==hg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Fc(a.D);Uf(a.ha);a.F=null;a.R=null};
g.mg=function(a,b){a=g.ia(a)?g.tc(a):a;b=g.zf(b);var c=g.kg+"_"+g.na(a),d=g.lg[c];if(d)return d.wp(b),d.api;d=new Xf(a,c);g.lg[c]=d;g.B("player-added",d.api);g.nb(d,g.v(dba,d));g.vb(function(){d.wp(b)},0);
return d.api};
dba=function(a){g.lg[a.getId()]=null};
g.ng=function(a){a=g.E(a);if(!a)return null;var b=g.kg+"_"+g.na(a),c=g.lg[b];c||(c=new Xf(a,b),g.lg[b]=c);return c.api};
g.og=function(){return g.D(g.E("page-container"),"remote-connected")};
eba=function(){g.n("yt.abuse.botguardInitialized",Bf,void 0);g.n("yt.abuse.invokeBotguard",g.Cf,void 0);g.n("yt.abuse.dclkstatus.checkDclkStatus",Df,void 0);g.n("yt.player.exports.navigate",g.Gf,void 0);g.n("yt.player.embed",g.mg,void 0);g.n("yt.player.getPlayerByElement",g.ng,void 0);g.n("yt.util.activity.init",g.he,void 0);g.n("yt.util.activity.getTimeSinceActive",g.ie,void 0);g.n("yt.util.activity.setTimestamp",ge,void 0);var a=g.q("ytplayer.config");pg(a);g.q("ytspf.enabled")&&(qg=g.wb(rg,5E3),
(a=g.sg())?(a.addEventListener("onReady",rg),a.addEventListener("onStateChange",rg)):tg("unable to init PP monitor"))};
pg=function(a){for(var b in g.lg){var c=g.lg[b];c&&c.cancel()}if(a=a||null){b=g.sg();var d=!0,c=g.ug;g.ug=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(vg="",g.mg("player-api",a)):b.playVideo();a=g.zf(a);a.loaded=!0}rg();g.n("ytplayer.config",a,void 0)};
g.sg=function(){var a=g.q("yt.player.getPlayerByElement");return a?a("player-api"):null};
rg=function(){var a=g.sg();if(a){var b;b=g.E("player");b=!b||g.D(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.y("PAGE_NAME"),e=g.og();!c||d||e||(tg("PP playing off watch (paused)"),a.pauseVideo());b&&d?tg("PP off-screen on watch"):b||d||tg("PP !off-screen off watch")}};
tg=function(a){var b=g.y("PAGE_NAME");b&&(b=[b,vg,g.q("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.n("yt.www.persistentplayer.issue",a,void 0),g.zb(Error(a),"WARNING"))};
g.wg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.xg=!1;this.Bw=!0};
g.xg=function(a,b){g.wg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.qo=!1;this.yb=null;a&&this.init(a,b)};
g.zg=function(a){return!(!a||!a[yg])};
gba=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.Nh=!!d;this.Bd=e;this.key=++fba;this.mh=this.jj=!1};
Ag=function(a){a.mh=!0;a.listener=null;a.A=null;a.src=null;a.Bd=null};
Bg=function(a){this.src=a;this.A={};this.C=0};
g.Dg=function(a,b,c,d,e,h){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.C++);var l=Cg(b,c,e,h);-1<l?(a=b[l],d||(a.jj=!1)):(a=new gba(c,a.src,k,!!e,h),a.jj=d,b.push(a));return a};
Eg=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.Ka(a.A[c],b);d&&(Ag(b),0==a.A[c].length&&(delete a.A[c],a.C--));return d};
g.Fg=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=Cg(a,c,d,e));return-1<b?a[b]:null};
Cg=function(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.mh&&h.listener==b&&h.Nh==!!c&&h.Bd==d)return e}return-1};
g.Gg=function(a,b,c,d,e){if(g.ga(b)){for(var h=0;h<b.length;h++)g.Gg(a,b[h],c,d,e);return null}c=g.Hg(c);return g.zg(a)?a.O(b,c,d,e):g.Ig(a,b,c,!1,d,e)};
g.Ig=function(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var k=!!e,l=g.Jg(a);l||(a[Kg]=l=new Bg(a));c=g.Dg(l,b,c,d,e,h);if(c.A)return c;d=hba();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Lg(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Mg++;return c};
hba=function(){var a=iba,b=Ng?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.Og=function(a,b,c,d,e){if(g.ga(b))for(var h=0;h<b.length;h++)g.Og(a,b[h],c,d,e);else c=g.Hg(c),g.zg(a)?a.Ya(b,c,d,e):a&&(a=g.Jg(a))&&(b=g.Fg(a,b,c,!!d,e))&&g.Pg(b)};
g.Pg=function(a){if(g.ja(a)||!a||a.mh)return!1;var b=a.src;if(g.zg(b))return Eg(b.Z,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.Nh):b.detachEvent&&b.detachEvent(Lg(c),d);Mg--;(c=g.Jg(b))?(Eg(c,a),0==c.C&&(c.src=null,b[Kg]=null)):Ag(a);return!0};
Lg=function(a){return a in Qg?Qg[a]:Qg[a]="on"+a};
Sg=function(a,b,c,d){var e=!0;if(a=g.Jg(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.Nh==c&&!h.mh&&(h=Rg(h,d),e=e&&!1!==h)}return e};
Rg=function(a,b){var c=a.listener,d=a.Bd||a.src;a.jj&&g.Pg(a);return c.call(d,b)};
iba=function(a,b){if(a.mh)return!0;if(!Ng){var c=b||g.q("window.event");b=new g.xg(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.xg&&0<=e;e--){b.currentTarget=c[e];var h=Sg(c[e],a,!0,b),d=d&&h}for(e=0;!b.xg&&e<c.length;e++)b.currentTarget=c[e],h=Sg(c[e],a,!1,b),d=d&&h}return d}return Rg(a,new g.xg(b,
this))};
g.Jg=function(a){a=a[Kg];return a instanceof Bg?a:null};
g.Hg=function(a){if(g.ka(a))return a;a[Tg]||(a[Tg]=function(b){return a.handleEvent(b)});
return a[Tg]};
g.Ug=function(){g.mb.call(this);this.Z=new Bg(this);this.Ly=this;this.Kl=null};
Wg=function(a,b,c,d){b=a.Z.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var k=b[h];if(k&&!k.mh&&k.Nh==c){var l=k.listener,p=k.Bd||k.src;k.jj&&Eg(a.Z,k);e=!1!==l.call(p,d)&&e}}return e&&0!=d.Bw};
g.Xg=function(a,b,c){if(g.ka(a))c&&(a=(0,g.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,g.t)(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:g.m.setTimeout(a,b||0)};
g.Yg=function(a){g.m.clearTimeout(a)};
g.Zg=function(a,b,c){g.mb.call(this);this.A=a;this.B=b||0;this.C=c;this.Rc=(0,g.t)(this.Nj,this)};
oba=function(){$g++;var a=g.xc(),b=new g.Ge(0,0,a.width,a.height);Xe("vps",a.width+"."+a.height);g.Ve("vpc");var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0;ah.start();for(var h=0;h<c;h++){var k=a[h];if(bh(k,b)){var l=jba(k);l.then(kba);d.push(l);ch.push(l);k.loadTime||(e=!1)}}e&&Xe("yt_eil",1);Xe("vpni",d.length);g.Ve("vpcc");b=g.ed(d).then(lba);g.gd(b,mba);b.then(nba);ch.push(b);return b};
nba=function(){ah.stop()};
mba=function(){g.Ve("vpr")};
bh=function(a,b){for(var c=window.document.body;a!=c;){var d=g.Mc(a);if(d in dh)break;var e=window.getComputedStyle(a);if("none"==e.display||"hidden"==e.visibility)return!1;e=a.getBoundingClientRect();if(!(b.left<=e.left+e.width&&e.left<=b.left+b.width&&b.top<=e.top+e.height&&e.top<=b.top+b.height))return!1;dh[d]=!0;a=a.parentElement}return!0};
lba=function(a){for(var b=g.xc(),b=new g.Ge(0,0,b.width,b.height),c=0,d=0,e=a.length;d<e;d++){var h=a[d].time;bh(a[d].C,b)&&c<h&&(c=h)}return c};
jba=function(a){var b=$g;return new g.$c(function(c,d){var e={C:a,time:0};if(a.loadTime)e.time=(0,window.parseInt)(a.loadTime,10),c(e);else{var h=g.G(a,"load",function(){$g!=b&&(g.ee(h),d());if(a.loadTime){var k=(0,window.parseInt)(a.loadTime,10);g.ee(h);e.time=k;c(e)}});
eh.push(h)}})};
kba=function(a){ah.start();Xe("vpil",++fh);a=a.time;gh<a&&(gh=a,g.Ve("lim",a))};
pba=function(){g.Ve("vptl",gh);g.Ve("vpl",gh)};
ih=function(){g.Ve("ol");window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Ve("cpt")},0)}):window.document.hidden?g.Ve("cpt"):(0,window.setTimeout)(function(){g.Ve("cpt")},0);
qba();g.y("CSI_VIEWPORT")&&(hh=oba(),hh.then(function(a){g.Ve("vpl",a);hh=null},function(){}))};
qba=function(){jh("init");var a=g.y("PAGE_NAME",void 0);a&&jh("init-"+a)};
jh=function(a){g.Jb()?kh.push(g.Kb(g.v(g.Ib,a),0)):g.B(a)};
lh=function(){g.Ob(kh);kh.length=0;for(var a=ch.length,b=0;b<a;b++)ch[b].cancel();gh=fh=ch.length=0;dh={};g.ee(eh);eh.length=0;hh&&(hh.cancel(),hh=null);(a=g.y("PAGE_NAME",void 0))&&g.Ib("dispose-"+a);g.Ib("dispose")};
rba=function(){ih()};
sba=function(){g.y("TIMING_REPORT_ON_UNLOAD")&&g.Ue(!0);of("u");g.Pc("actually_send_abandonment_pings")&&g.xd();lh();g.Ib("pageunload")};
mh=function(){ge()};
nh=function(a){a=a.detail.url;window.yt_spf_loaded_history=!0;ge();var b=g.je();if(b&&a){var c=g.ud(b.visualElement),b={csn:b.clientScreenNonce};"trackingParams"in c?b.itct=c.trackingParams:(b.veType=c.veType,b.veCounter=c.veCounter);g.wf(a,b)}};
sh=function(){oh=1;ph=qh=0;g.y("TIMING_REPORT_ON_UNLOAD")&&g.Ue(!0);of("n");bf();Ye("n");Oe("nr");rh(tba);g.Ib("navigate")};
wh=function(a){a=a.detail.part||a.detail.partial;g.Ve("nc"+qh);++qh;if(a.data&&a.data.deferDispose)"watch"==a.name&&g.Ve("bc");else{var b=1==oh;oh=2;b?(rh(uba),th()):rh(vba);if(b=a.data&&a.data.swfcfg)uh(a.timing,b.args),vh(b)}};
xh=function(){g.Ve("np"+ph);++ph};
yh=function(a){a=a.detail.response;var b=1==oh;oh=3;b&&(rh(wba),th());if(b=a.data&&a.data.swfcfg)uh(a.timing,b.args),vh(b)};
Bh=function(a){g.Ve("nd");a=a.detail.response;g.zh=a.cacheKey;a=a.timing;var b=window._spf_state;Xe("yt_nav",b&&b["nav-counter"]||0);Ye("ne",a.responseStart);Xe("srt",Math.max(0,a.responseStart-a.navigationStart));Xe("yt_lt",a.spfCached?"hot":"warm");Xe("yt_pft",+!!a.spfPrefetched);g.Ve("pfs",a.fetchStart);g.Ve("pfrs",a.responseStart);"redirectStart"in a&&cf(a);rh(Ah);window.document.getElementById("content").style.height="";ih();oh=0};
Ch=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.zb(a)};
Dh=function(a){g.xf(g.ue({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
yba=function(){xba();g.tb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
zba=function(){};
th=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");lh();var a=g.y("TIMING_ACTION"),b;for(b in g.sb)delete g.sb[b];g.tb("PREVIOUS_ACTION",a);g.n("ytplayer.config",null,void 0);if((b=g.sg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())vg=b,(b=g.E("movie_player"))&&b.stopVideo?(b.stopVideo(),vg="recovered"):vg="missing2"}else vg="missing";rg()};
vh=function(a){"cfg"in Qe(void 0)||g.Ve("cfg");pg(a)};
rh=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Nb(Eh);Eh=g.Lb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.xb(Fh);Fh=g.vb(function(){b.className=e},c)},0)};
xba=function(){var a=Ah[0]+50;g.xb(Fh);Fh=g.vb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
uh=function(a,b){var c=a&&a.spfCached;a=a&&a.spfPrefetched;var d=[];c&&!a&&(0,g.A)(Aba,function(a){a in b&&(delete b[a],d.push(a))});
g.y("EXP_DEBUG_PREFETCH")&&(d.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:a,deleted:d.join("")},g.xf(g.ue(c)))};
Cba=function(a){if(g.Gh&&!g.Hh&&!g.Ih&&!g.Jh&&a.pushManager)if("default"!=window.Notification.permission)Kh().then(Bba);else if(g.y("SERVICE_WORKER_PROMPT_NOTIFICATIONS",void 0)&&g.y("LOGGED_IN",void 0))if(g.Pc("service_worker_push_ticker_enabled")){if((a=window.document.getElementById("ticker"))&&"TRIGGER_CONDITION_ENABLE_NOTIFICATIONS_PROMPT"==a.dataset.triggerCondition){var b=a.querySelector(".yt-uix-button-alert-info");b&&(b.addEventListener("click",Lh),a.classList.add("show"))}}else Lh()};
Lh=function(){window.Notification.requestPermission().then(function(a){var b=window.document.getElementById("ticker");b.className=b.classList.remove("show");"granted"==a?window.navigator.serviceWorker.getRegistration().then(function(){Kh().then(Mh)}):"denied"==a&&Mh()})};
Kh=function(){return window.navigator.serviceWorker.getRegistration().then(function(a){return a?a.pushManager.getSubscription().then(function(b){return b?window.Promise.resolve():a.pushManager.subscribe({userVisibleOnly:!0}).then(function(){return window.Promise.resolve()},function(){return window.Promise.resolve()})}):window.Promise.resolve()})};
Mh=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_register",data:g.y("ID_TOKEN")})};
Bba=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_check_registration",data:g.y("ID_TOKEN")})};
Dba=function(){var a="/sw.js",b=g.y("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"});g.Pc("service_worker_push_enabled")&&window.navigator.serviceWorker.ready.then(Cba)};
Eba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"})};
Nh=function(){g.Pb.call(this,"www/base");this.B=0};
Oh=function(a){(a=a.detail.name)&&Sb(a)};
g.aa=[];g.Ph=g.Ph||{};g.m=this;ma="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.Ud=Date.now||function(){return+new Date};g.oa[" "]=g.da;g.w(g.sa,Error);g.sa.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.Qh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.Fba=2147483648*Math.random()|0;g.Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ia(a))return g.ia(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Gba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ia(a))return g.ia(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.A=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ia(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.Rh=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.ia(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var p=k[l];
b.call(c,p,l,a)&&(e[h++]=p)}return e};
g.gf=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.ia(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.Sh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.t)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.A)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.Th=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ia(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.Uh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ia(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.Vh=g.Ma(!1);g.Wh=g.Ma(!0);g.Xh=g.Ma(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Yh=g.m.navigator;if(Yh){var Zh=Yh.userAgent;if(Zh){g.Xa=Zh;break a}}g.Xa=""};var lb;bb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var ib=new bb(function(){return new eb},function(a){a.reset()},100);
db.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
eb.prototype.set=function(a,b){this.uc=a;this.scope=b;this.next=null};
eb.prototype.reset=function(){this.next=this.scope=this.uc=null};var fb,gb=!1,hb=new db;g.mb.prototype.rd=!1;g.mb.prototype.hb=function(){return this.rd};
g.mb.prototype.dispose=function(){this.rd||(this.rd=!0,this.W())};
g.mb.prototype.W=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};g.w(g.qb,g.mb);g.f=g.qb.prototype;g.f.subscribe=function(a,b,c){var d=this.Ed[a];d||(d=this.Ed[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.Ed[a]){var d=this.A;if(a=g.Ga(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Fd(a)}return!1};
g.f.Fd=function(a){var b=this.A[a];if(b){var c=this.Ed[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.da):(c&&g.Ka(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.Ha=function(a,b){var c=this.Ed[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.Fd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.Ed[a];b&&((0,g.A)(b,this.Fd,this),delete this.Ed[a])}else this.A.length=0,this.Ed={}};
g.f.pb=g.ba(3);g.f.W=function(){g.qb.L.W.call(this);this.clear();this.C.length=0};g.sb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.n("yt.config_",g.sb,void 0);g.n("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Ab=window.yt&&window.yt.msgs_||g.q("window.ytcfg.msgs")||{};g.n("yt.msgs_",g.Ab,void 0);g.Cd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Kf="Microsoft Internet Explorer"==window.navigator.appName;var Hba=g.q("yt.pubsub.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.Fd;g.qb.prototype.publish=g.qb.prototype.Ha;g.qb.prototype.clear=g.qb.prototype.clear;g.n("yt.pubsub.instance_",Hba,void 0);var Eb=g.q("yt.pubsub.subscribedKeys_")||{};g.n("yt.pubsub.subscribedKeys_",Eb,void 0);var Gb=g.q("yt.pubsub.topicToKeys_")||{};g.n("yt.pubsub.topicToKeys_",Gb,void 0);var Fb=g.q("yt.pubsub.isSynchronous_")||{};
g.n("yt.pubsub.isSynchronous_",Fb,void 0);var Db=g.q("yt.pubsub.skipSubId_")||null;g.n("yt.pubsub.skipSubId_",Db,void 0);g.f=g.Pb.prototype;g.f.kP=function(){this.kk()||this.init()};
g.f.enable=function(){this.A=1;(0,g.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.kP,this),this.subscribe("dispose-"+a,this.dispose,this),g.y("PAGE_NAME")==a&&g.Qb(this))},this)};
g.f.init=function(){g.Nb(this.C);this.A=2;this.H&&this.H()};
g.f.kk=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Nb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.zb(a)}};
g.f.subscribe=function(a,b,c){a=g.z(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Hb(this.D);this.D=[]};var Rb=g.q("yt.modules.registry_")||{};g.n("yt.modules.registry_",Rb,void 0);g.Vb.prototype.mg=!0;g.Ub={};g.Vb.prototype.hf=function(){return this.A};
g.Iba=g.Wb("");g.Yb.prototype.mg=!0;g.Yb.prototype.hf=function(){return this.A};
g.Yb.prototype.rn=!0;g.Yb.prototype.ef=g.ba(5);var oaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Xb={};g.$b("about:blank");g.cc.prototype.rn=!0;g.cc.prototype.ef=g.ba(4);g.cc.prototype.mg=!0;g.cc.prototype.hf=function(){return this.A};
g.bc={};g.Jba=g.dc("<!DOCTYPE html>",0);g.$h=g.dc("",0);g.ai=g.dc("<br>",0);var gc={};var paa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,qaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.f=g.kc.prototype;g.f.clone=function(){return new g.kc(this.x,this.y)};
g.f.equals=function(a){return a instanceof g.kc&&g.lc(this,a)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){b=g.ja(b)?b:a;this.x*=a;this.y*=b;return this};g.f=g.mc.prototype;g.f.clone=function(){return new g.mc(this.width,this.height)};
g.f.Lg=function(){return this.width*this.height};
g.f.aspectRatio=function(){return this.width/this.height};
g.f.isEmpty=function(){return!this.Lg()};
g.f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){b=g.ja(b)?b:a;this.width*=a;this.height*=b;return this};var hi,ii,raa,mi;g.bi=g.Ya("Opera");g.F=g.Za();g.ci=g.Ya("Edge");g.di=g.ci||g.F;g.ei=g.Ya("Gecko")&&!(g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Bc=g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Bc&&g.Ya("Mobile");g.fi=g.Ya("Macintosh");g.gi=g.Ya("Windows");g.Kba=g.Ya("Linux")||g.Ya("CrOS");hi=g.m.navigator||null;hi&&g.ya(hi.appVersion||"","X11");g.Lba=g.Ya("Android");g.Ih=g.nc();g.Jh=g.Ya("iPad");g.Mba=g.Ya("iPod");
a:{var ji="",ki=function(){var a=g.Xa;if(g.ei)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.ci)return/Edge\/([\d\.]+)/.exec(a);if(g.F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Bc)return/WebKit\/(\S+)/.exec(a);if(g.bi)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
ki&&(ji=ki?ki[1]:"");if(g.F){var li=oc();if(null!=li&&li>(0,window.parseFloat)(ji)){ii=String(li);break a}}ii=ji}g.pc=ii;raa={};var ni=g.m.document;mi=ni&&g.F?oc()||("CSS1Compat"==ni.compatMode?(0,window.parseInt)(g.pc,10):5):void 0;g.rc=mi;var saa;saa=!g.F||g.sc(9);g.Nba=!g.ei&&!g.F||g.F&&g.sc(9)||g.ei&&g.qc("1.9.1");g.ri=g.F&&!g.qc("9");g.Oba=g.F||g.bi||g.Bc;g.Pba=g.F&&!g.sc(9);var uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};var waa=g.Bc?"webkit":g.ei?"moz":g.F?"ms":g.bi?"o":"",Lc=g.q("yt.dom.getNextId_");if(!Lc){Lc=function(){return++Qba};
g.n("yt.dom.getNextId_",Lc,void 0);var Qba=0};g.Sc.prototype.Wb=function(a){var b=[];Uc(this,a,b);return b.join("")};
var Wc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;ad.prototype.reset=function(){this.context=this.C=this.B=this.A=null;this.D=!1};
var bd=new bb(function(){return new ad},function(a){a.reset()},100);
g.$c.prototype.then=function(a,b,c){return fd(this,g.ka(a)?a:null,g.ka(b)?b:null,c)};
g.Xc(g.$c);g.$c.prototype.cancel=function(a){0==this.A&&jb(function(){var b=new g.md(a);hd(this,b)},this)};
g.$c.prototype.R=function(a){this.A=0;g.Zc(this,2,a)};
g.$c.prototype.Z=function(a){this.A=0;g.Zc(this,3,a)};
g.$c.prototype.G=function(){for(var a;a=id(this);)jd(this,a,this.A,this.K);this.H=!1};
var od=ab;g.w(g.md,g.sa);g.md.prototype.name="cancel";var rd=null;sd.prototype.D=function(){var a=g.q("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);var b=this.A.apiaryHost;g.va(g.za(b))||a("googleapis.config/root",(-1==b.indexOf("://")?"//":"")+b);b=this.A.gq;g.va(g.za(b))||a("googleapis.config/root-1p",(-1==b.indexOf("://")?"//":"")+b);a("googleapis.config/sessionIndex",g.y("SESSION_INDEX"));g.q("gapi.client.setApiKey")(this.A.innertubeApiKey)};
sd.prototype.C=function(){return{context:g.qd(this.A)}};
sd.prototype.B=function(a,b,c){var d,e=!1;0<c.timeout&&(d=g.vb(function(){e||(e=!0,c.zc&&c.zc())},c.timeout));
Caa(this,a,b,function(a){if(!e)if(e=!0,d&&g.xb(d),a)c.X&&c.X(a);else if(c.onError)c.onError()})};var Daa,wd;Daa={log_event:"events",log_interaction:"interactions"};g.Bd={};wd={};g.Ad=0;g.vd=g.q("yt.logging.transport.logsQueue_")||{};g.n("yt.logging.transport.logsQueue_",g.vd,void 0);g.Fd="StopIteration"in g.m?g.m.StopIteration:{message:"StopIteration",stack:""};g.Ed.prototype.next=function(){throw g.Fd;};
g.Ed.prototype.Zb=function(){return this};Jd.prototype.set=g.r;Jd.prototype.get=g.r;Jd.prototype.remove=g.r;g.w(g.Kd,Jd);g.Kd.prototype.pb=g.ba(2);g.Kd.prototype.Zb=g.r;g.Kd.prototype.clear=function(){var a=g.Id(this.Zb(!0)),b=this;(0,g.A)(a,function(a){b.remove(a)})};g.w(g.Ld,g.Kd);g.f=g.Ld.prototype;g.f.isAvailable=function(){if(!this.A)return!1;try{return this.A.setItem("__sak","1"),this.A.removeItem("__sak"),!0}catch(a){return!1}};
g.f.set=function(a,b){try{this.A.setItem(a,b)}catch(c){if(0==this.A.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};
g.f.get=function(a){a=this.A.getItem(a);if(!g.ia(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
g.f.remove=function(a){this.A.removeItem(a)};
g.f.pb=g.ba(1);g.f.Zb=function(a){var b=0,c=this.A,d=new g.Ed;d.next=function(){if(b>=c.length)throw g.Fd;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!g.ia(d))throw"Storage mechanism: Invalid value was encountered";return d};
return d};
g.f.clear=function(){this.A.clear()};
g.f.key=function(a){return this.A.key(a)};g.w(g.Md,g.Ld);g.w(Od,g.Ld);g.Pd.prototype.set=function(a,b){g.ca(b)?this.A.set(a,g.Tc(b)):this.A.remove(a)};
g.Pd.prototype.get=function(a){var b;try{b=this.A.get(a)}catch(c){return}if(null!==b)try{return g.Rc(b)}catch(c){throw"Storage: Invalid value was encountered";}};
g.Pd.prototype.remove=function(a){this.A.remove(a)};g.w(Qd,g.Pd);Qd.prototype.set=function(a,b){Qd.L.set.call(this,a,Sd(b))};
Qd.prototype.C=function(a){a=Qd.L.get.call(this,a);if(!g.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};
Qd.prototype.get=function(a){if(a=this.C(a)){if(a=a.data,!g.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};g.w(g.Td,Qd);g.Td.prototype.set=function(a,b,c){if(b=Sd(b)){if(c){if(c<(0,g.Ud)()){g.Td.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,g.Ud)()}g.Td.L.set.call(this,a,b)};
g.Td.prototype.C=function(a,b){var c=g.Td.L.C.call(this,a);if(c)if(!b&&g.Vd(c))g.Td.prototype.remove.call(this,a);else return c};g.w(g.Wd,g.Td);var si,ti;si=new g.Md;g.Yd=si.isAvailable()?new g.Wd(si):null;ti=new Od;g.Xd=ti.isAvailable()?new g.Wd(ti):null;g.Wf=g.Ya("Firefox");g.ui=g.nc()||g.Ya("iPod");g.vi=g.Ya("iPad");g.Hh=g.Ya("Android")&&!(g.$a()||g.Ya("Firefox")||g.Ya("Opera")||g.Ya("Silk"));g.Gh=g.$a();g.wi=g.Ya("Safari")&&!(g.$a()||g.Ya("Coast")||g.Ya("Opera")||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.nc()||g.Ya("iPad")||g.Ya("iPod"));g.Rba=g.ei||g.Bc&&!g.wi||g.bi||"function"==typeof g.m.btoa;g.$d.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.$d.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.$d.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Eaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};var nf=(0,g.Ud)().toString();g.be=g.q("yt.events.listeners_")||{};g.n("yt.events.listeners_",g.be,void 0);var de=g.q("yt.events.counter_")||{count:0};g.n("yt.events.counter_",de,void 0);g.ne=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;var ye={},Iaa=0;g.ze.prototype.Wb=function(){return{version:this.version,args:this.args}};
g.Ae.prototype.toString=function(){return this.topic};var Sba=g.q("yt.pubsub2.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.Fd;g.qb.prototype.publish=g.qb.prototype.Ha;g.qb.prototype.clear=g.qb.prototype.clear;g.n("yt.pubsub2.instance_",Sba,void 0);g.xi=g.q("yt.pubsub2.subscribedKeys_")||{};g.n("yt.pubsub2.subscribedKeys_",g.xi,void 0);g.yi=g.q("yt.pubsub2.topicToKeys_")||{};g.n("yt.pubsub2.topicToKeys_",g.yi,void 0);g.zi=g.q("yt.pubsub2.isAsync_")||{};
g.n("yt.pubsub2.isAsync_",g.zi,void 0);g.n("yt.pubsub2.skipSubKey_",null,void 0);var Ne=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.w(De,g.ze);var Uaa=new g.Ae("timing-sent",De);g.f=g.Ee.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.Ee(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Fe(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){b=g.ja(b)?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};g.f=g.Ge.prototype;g.f.clone=function(){return new g.Ge(this.left,this.top,this.width,this.height)};
g.f.contains=function(a){return a instanceof g.kc?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.f.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){b=g.ja(b)?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};Le.prototype.toString=function(){return this.region.toString()+": "+this.timing+" => "+this.url};
Me.prototype.toString=function(){return["progress",this.progress,"timing",this.timing,"area",this.Lg].join(": ")};
Ke.C=.1;Ke.A=/url\(["']?(http[^'"\)]+)['"]?\)/i;Ke.B="mark_iframe_loaded: ";Ke.D=20;var Saa={vc:!0},Laa=/^mark_/i,ef={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="player-plasma-phone/base"]':"mpppj",'script[name="player-plasma-tablet/base"]':"mpptj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},
Ze={ad_at:"adType",cpn:"clientPlaybackNonce",csn:"clientScreenNonce",yt_lt:"loadType",yt_ad:"isMonetized",yt_ad_pr:"prerollAllowed",yt_red:"isRedSubscriber",yt_vis:"isVisible"},Naa=["isMonetized","prerollAllowed","isRedSubscriber","isVisible"],Oaa=(0,g.t)(Ne.clearResourceTimings||Ne.webkitClearResourceTimings||Ne.mozClearResourceTimings||Ne.msClearResourceTimings||Ne.oClearResourceTimings||g.da,Ne);g.qf=/\s*;\s*/;g.f=g.pf.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.Ud)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.qf),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Pb=g.ba(6);g.f.ob=g.ba(7);g.f.isEmpty=function(){return!this.A.cookie};
g.f.pb=g.ba(0);g.f.Be=g.ba(8);g.f.clear=function(){for(var a=g.rf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.sf=new g.pf("undefined"==typeof window.document?null:window.document);g.sf.C=3950;var Vaa={enablejsapi:1},Waa={},Xaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};yf.prototype.clone=function(){var a=new yf,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.fa(c)?a[b]=g.Ua(c):a[b]=c}return a};g.Af=null;g.Ai=g.F?"focusin":"DOMFocusIn";g.Bi=g.F?"focusout":"DOMFocusOut";g.Ci=g.Bc?"webkitTransitionEnd":g.bi?"otransitionend":"transitionend";g.Di=g.ei?"MozUserSelect":g.Bc||g.ci?"WebkitUserSelect":null;g.ea(g.Lf);g.Lf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Yaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var eg;var Ei=g.Xa,Ei=Ei.toLowerCase();if(g.ya(Ei,"android")){var Fi=Ei.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Fi)eg=Number(Fi[1]);else{var Gi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Hi=Ei.match("("+g.Oa(Gi).join("|")+")");eg=Hi?Gi[Hi[0]]:0}}else eg=void 0;var aba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],bba=['audio/mp4; codecs="mp4a.40.2"'];g.w(Rf,g.mb);Rf.prototype.Ya=function(a){for(var b=0;b<this.A.length;b++)if(this.A[b]==a){this.A.splice(b,1);a.target.removeEventListener(a.name,a.Nb);break}};
Rf.prototype.W=function(){Uf(this);Rf.L.W.call(this)};var Zaa={"api.invalidparam":2,auth:150,"drm.auth":150,"heartbeat.net":150,"heartbeat.servererror":150,"heartbeat.stop":150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.w(Xf,g.mb);var $aa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=Xf.prototype;g.f.getId=function(){return this.ka};
g.f.wp=function(a,b){this.hb()||(Zf(this,a),cg(this,b),this.H&&$f(this))};
g.f.GA=function(){return this.kb};
g.f.SQ=function(){if(!this.ba){var a=fg(this);a&&"html5"==hg(this)?(this.G="html5",this.H||this.lh()):(ig(this),this.G="html5",a&&this.M?(this.D.appendChild(this.M),this.lh()):(this.A.loaded=!0,this.P=(0,g.t)(function(){var a=this.D,c=this.A.clone();g.q("yt.player.Application.create")(a,c);this.lh()},this),this.ba=!0,a?this.P():(g.ic(this.A.assets.js,this.P),g.Qf(this.A.assets.css))))}};
g.f.RQ=function(){var a=this.A.clone();if(!this.F){var b=bg(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,Tf(this.ha,this.F,"focus",this.Tu),this.R=window.document.createElement("span"),this.R.tabIndex=0,Tf(this.ha,this.R,"focus",this.Tu),g.Gc(this.F,b),g.Hc(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==hg(this)?(this.G="flash",this.H||this.lh()):(ig(this),this.G="flash",this.A.loaded=!0,b=g.Lf.getInstance(),b=g.Nf(b)||!g.Of(b)?
a.url:a.urlV9As2,window!=window.top&&window.document.referrer&&(a.args.framer=window.document.referrer.substring(0,128)),g.Pf(this.D,b,a),this.lh())};
g.f.Tu=function(){bg(this).focus()};
g.f.lh=function(){if(!this.hb()){var a=bg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.ba=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))dg(this);else{Vf(this);this.H=!0;a=bg(this);a.addEventListener&&(this.U=gg(this,a,"addEventListener"));a.removeEventListener&&(this.na=gg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=gg(this,a,d))}for(var e in this.B)this.U(e,
this.B[e]);$f(this);this.Ga&&this.Ga(this.api);this.Y.Ha("onReady",this.api)}else this.ub=g.vb((0,g.t)(this.lh,this),50)}};
g.f.fR=function(){return this.H};
g.f.ve=function(a,b){if(!this.hb()&&(b=Yf(this,b))){if(!g.Ia(this.Cb,a)&&!this.B[a]){var c=cba(this,a);this.U&&this.U(a,c)}this.Y.subscribe(a,b);"onReady"==a&&this.H&&g.vb(g.v(b,this.api),0)}};
g.f.YO=function(a,b){this.hb()||(b=Yf(this,b))&&this.Y.unsubscribe(a,b)};
g.f.Jz=function(a){a=a?vaa:uaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.Zp=function(a){g.B("a11y-announce",a)};
g.f.DK=function(a){dg(this,a)};
g.f.GK=function(a){g.B("WATCH_LATER_VIDEO_ADDED",a)};
g.f.HK=function(a){g.B("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.lK=function(){this.eb||(g.Gh?(this.bb=g.Ac(window.document),Tf(this.Z,window,"scroll",this.cN),Tf(this.Z,this.D,"touchmove",this.CM)):(Tf(this.Z,this.D,"mousewheel",this.hv),Tf(this.Z,this.D,"wheel",this.hv)),this.eb=!0)};
g.f.mK=function(){Uf(this.Z);this.eb=!1};
g.f.hv=function(a){g.fe(a)};
g.f.cN=function(){window.scrollTo(this.bb.x,this.bb.y)};
g.f.CM=function(a){a.preventDefault()};
g.f.zB=function(){return this.G||hg(this)};
g.f.iB=function(){return this.mb};
g.f.cancel=function(){if(this.P){var a=this.P,b=g.hc(this.A.assets.js);window.spf.script.ignore(b,a)}g.xb(this.ub);this.ba=!1};
g.f.W=function(){ig(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.zb(b)}this.Ua=null;for(var a in this.B)g.m[this.B[a]]=null;this.kb=this.A=this.api=null;delete this.D;delete this.K;Xf.L.W.call(this)};g.lg={};g.kg="player_uid_"+(1E9*Math.random()>>>0);var Tba=g.q("yt.abuse.botguardInitialized")||Bf;g.n("yt.abuse.botguardInitialized",Tba,void 0);var Uba=g.q("yt.abuse.invokeBotguard")||g.Cf;g.n("yt.abuse.invokeBotguard",Uba,void 0);var Vba=g.q("yt.abuse.dclkstatus.checkDclkStatus")||Df;g.n("yt.abuse.dclkstatus.checkDclkStatus",Vba,void 0);var Wba=g.q("yt.player.exports.navigate")||g.Gf;g.n("yt.player.exports.navigate",Wba,void 0);var Xba=g.q("yt.player.embed")||g.mg;g.n("yt.player.embed",Xba,void 0);var Yba=g.q("yt.player.getPlayerByElement")||g.ng;
g.n("yt.player.getPlayerByElement",Yba,void 0);var Zba=g.q("yt.util.activity.init")||g.he;g.n("yt.util.activity.init",Zba,void 0);var $ba=g.q("yt.util.activity.getTimeSinceActive")||g.ie;g.n("yt.util.activity.getTimeSinceActive",$ba,void 0);var aca=g.q("yt.util.activity.setTimestamp")||ge;g.n("yt.util.activity.setTimestamp",aca,void 0);var qg,vg;g.ug=null;vg="";g.wg.prototype.stopPropagation=function(){this.xg=!0};
g.wg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Bw=!1};var Ng,cca;g.bca=!g.F||g.sc(9);Ng=!g.F||g.sc(9);cca=g.F&&!g.qc("9");!g.Bc||g.qc("528");g.ei&&g.qc("1.9b")||g.F&&g.qc("8")||g.bi&&g.qc("9.5")||g.Bc&&g.qc("528");g.ei&&!g.qc("8")||g.F&&g.qc("9");g.w(g.xg,g.wg);
g.xg.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?g.ei&&(g.qa(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.offsetX=g.Bc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Bc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.qo=g.fi?a.metaKey:a.ctrlKey;this.state=a.state;this.yb=a;a.defaultPrevented&&this.preventDefault()};
g.xg.prototype.stopPropagation=function(){g.xg.L.stopPropagation.call(this);this.yb.stopPropagation?this.yb.stopPropagation():this.yb.cancelBubble=!0};
g.xg.prototype.preventDefault=function(){g.xg.L.preventDefault.call(this);var a=this.yb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,cca)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.xg.prototype.Nr=g.ba(9);var yg="closure_listenable_"+(1E6*Math.random()|0),fba=0;Bg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=Cg(e,b,c,d);return-1<b?(Ag(e[b]),g.Ja(e,b),0==e.length&&(delete this.A[a],this.C--),!0):!1};
Bg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,Ag(d[e]);delete this.A[c];this.C--}return b};var Kg="closure_lm_"+(1E6*Math.random()|0),Qg={},Mg=0,Tg="__closure_events_fn_"+(1E9*Math.random()>>>0);g.w(g.Ug,g.mb);g.Ug.prototype[yg]=!0;g.f=g.Ug.prototype;g.f.Jj=function(){return this.Kl};
g.f.Oi=g.ba(10);g.f.addEventListener=function(a,b,c,d){g.Gg(this,a,b,c,d)};
g.f.removeEventListener=function(a,b,c,d){g.Og(this,a,b,c,d)};
g.f.dispatchEvent=function(a){var b,c=this.Jj();if(c){b=[];for(var d=1;c;c=c.Jj())b.push(c),++d}c=this.Ly;d=a.type||a;if(g.ia(a))a=new g.wg(a,c);else if(a instanceof g.wg)a.target=a.target||c;else{var e=a;a=new g.wg(d,c);g.Wa(a,e)}var e=!0,h;if(b)for(var k=b.length-1;!a.xg&&0<=k;k--)h=a.currentTarget=b[k],e=Wg(h,d,!0,a)&&e;a.xg||(h=a.currentTarget=c,e=Wg(h,d,!0,a)&&e,a.xg||(e=Wg(h,d,!1,a)&&e));if(b)for(k=0;!a.xg&&k<b.length;k++)h=a.currentTarget=b[k],e=Wg(h,d,!1,a)&&e;return e};
g.f.W=function(){g.Ug.L.W.call(this);this.removeAllListeners();this.Kl=null};
g.f.O=function(a,b,c,d){return g.Dg(this.Z,String(a),b,!1,c,d)};
g.f.Ya=function(a,b,c,d){return this.Z.remove(String(a),b,c,d)};
g.f.removeAllListeners=function(a){return this.Z?this.Z.removeAll(a):0};g.w(g.Zg,g.mb);g.f=g.Zg.prototype;g.f.xb=0;g.f.W=function(){g.Zg.L.W.call(this);this.stop();delete this.A;delete this.C};
g.f.start=function(a){this.stop();this.xb=g.Xg(this.Rc,g.ca(a)?a:this.B)};
g.f.stop=function(){this.isActive()&&g.Yg(this.xb);this.xb=0};
g.f.isActive=function(){return 0!=this.xb};
g.f.Nj=function(){this.xb=0;this.A&&this.A.call(this.C)};var eh=[],fh=0,gh=0,ch=[],$g=0,dh={},ah=new g.Zg(pba,1E3);var hh=null,kh=[];var oh,Fh,Eh,qh,ph,Aba,tba,wba,uba,vba,Ah;qh=0;ph=0;Aba=["server_prefetched_vast","vmap"];tba=[900,60,"waiting"];wba=[500,99,"waiting"];uba=[300,60,"waiting"];vba=[400,99,"waiting"];Ah=[300,101,"done"];window.yt=window.yt||{};g.n("yt.setConfig",g.tb,void 0);g.n("yt.pushConfigArray",function(a,b){var c=g.y(a,void 0);c?c.push(b):g.tb(a,[b])},void 0);
g.n("yt.getConfig",g.y,void 0);g.n("yt.hasMsg",g.Bb,void 0);g.n("yt.pubsub.publish",g.B,void 0);g.n("yt.pubsub.subscribe",g.z,void 0);g.n("yt.setMsg",function(a){rb(g.Ab,arguments)},void 0);
g.n("yt.setGoogMsg",function(a){rb(g.Ab,arguments)},void 0);
g.n("ytcsi.tick",g.Ve,void 0);g.w(Nh,g.Pb);
Nh.prototype.enable=function(){window.onload=rba;window.onunload=sba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",mh),window.addEventListener("spfhistory",nh),window.addEventListener("spfrequest",sh),window.addEventListener("spfpartprocess",wh),window.addEventListener("spfpartdone",xh),window.addEventListener("spfprocess",yh),window.addEventListener("spfdone",Bh),window.addEventListener("spferror",Ch),window.addEventListener("spfreload",
Dh),window.addEventListener("spfjsbeforeunload",Oh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",yba),this.subscribe("dispose",zba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Nh.prototype.init=function(){Nh.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.y("PAGEFRAME_JS")?(b=g.y("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.q("ytbin.www.pageframe.setup")()}):a&&(a=g.q("yt.www.masthead.loadSearchbox"))&&a();
var a=g.y("JS_COMMON_MODULE"),d=g.y("JS_PAGE_MODULES");d||(d=[a]);a=g.y("JS_DELAY_LOAD",0);0<a?(g.xb(this.B),this.B=g.vb(function(){b&&g.ic(b,c);window.spf.script.require(d)},a)):(b&&g.ic(b,c),window.spf.script.require(d));
eba();Raa();Maa();lf(!0);g.Ue(!1);g.y("SERVICE_WORKER_KILLSWITCH",void 0)||"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Pc("service_worker_enabled")?Dba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(Eba))};
Nh.prototype.dispose=function(){g.xb(this.B);var a=g.q("ytbin.www.pageframe.cancelSetup");a&&a();g.yb(qg);if(a=g.sg())a.removeEventListener("onReady",rg),a.removeEventListener("onStateChange",rg);lf(!1);Nh.L.dispose.call(this)};
Nh.prototype.disable=function(){Nh.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",mh),window.removeEventListener("spfhistory",nh),window.removeEventListener("spfrequest",sh),window.removeEventListener("spfpartprocess",wh),window.removeEventListener("spfpartdone",xh),window.removeEventListener("spfprocess",yh),window.removeEventListener("spfdone",Bh),window.removeEventListener("spferror",Ch),window.removeEventListener("spfreload",Dh),window.removeEventListener("spfjsbeforeunload",
Oh));window.onload=null;window.onunload=null;window.onerror=null};
g.Tb(new Nh);})(_yt_www);
